# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ZotPlanner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ZotPlanner
  pod 'Alamofire'
  pod 'QVRWeekView'
  pod 'FSCalendar'

  target 'ZotPlannerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ZotPlannerUITests' do
    # Pods for testing
  end

end
